#include QMK_KEYBOARD_H
void keyboard_post_init_user(void) {
  debug_enable=true;
  debug_matrix=true;
}
const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
    [0] = LAYOUT(
        KC_TAB, KC_Q , KC_W , KC_E , KC_R , KC_T , KC_Y , KC_U , KC_I , KC_O ,KC_P, KC_SEMICOLON,
        KC_CAPS, KC_A , KC_S , KC_D , KC_F , KC_G , KC_H , KC_J , KC_K , KC_L , KC_QUOTE, KC_SLSH,
        KC_LEFT_CTRL, KC_Z, KC_X , KC_C , KC_V , KC_B , KC_N , KC_M ,KC_COMM ,KC_DOT , KC_PGDN, KC_PGUP,
        KC_PRINT_SCREEN, KC_LEFT_ALT , KC_DELETE,KC_SPC, KC_ENTER, KC_ENTER, KC_SPC, KC_BACKSPACE, KC_HOME, KC_END,
        MO(2), KC_LEFT_SHIFT, KC_RIGHT_SHIFT, MO(1)
        ),
    [1] = LAYOUT(
        KC_GRAVE , KC_7 , KC_8 , KC_9 ,  KC_0 ,  LSFT(KC_LEFT_BRACKET) , LSFT(KC_RIGHT_BRACKET) , KC_LEFT_BRACKET , KC_RIGHT_BRACKET , KC_NO, KC_NO , KC_NO ,
        KC_ESC , KC_4 , KC_5 , KC_6 ,  KC_EQUAL , KC_MINUS , KC_LEFT , KC_DOWN , KC_UP , KC_RIGHT , KC_NO, KC_BACKSLASH,
        KC_RIGHT_CTRL ,KC_1 , KC_2 , KC_3 , KC_NO , KC_NO , KC_NO , KC_NO , KC_COMM ,KC_DOT , KC_NO , KC_NO ,
        KC_NO , KC_NO , KC_NO , KC_NO , KC_NO , KC_NO , KC_NO , KC_NO , KC_NO , KC_NO ,
        KC_NO, KC_LEFT_SHIFT, KC_RIGHT_SHIFT, KC_NO
        ),
    [2] = LAYOUT(
        LSFT(KC_GRAVE) , LSFT(KC_7) , LSFT(KC_8) , LSFT(KC_9) , LSFT(KC_0) , LSFT(KC_LEFT_BRACKET) , LSFT(KC_RIGHT_BRACKET) , KC_LEFT_BRACKET , KC_RIGHT_BRACKET , KC_NO,KC_NO, KC_NO ,
        KC_NO , LSFT(KC_4) , LSFT(KC_5) , LSFT(KC_6) , LSFT(KC_EQUAL) , LSFT(KC_MINUS) , KC_LEFT , KC_DOWN , KC_UP , KC_RIGHT , KC_NO, LSFT(KC_BACKSLASH),
        KC_RIGHT_CTRL , LSFT(KC_1) , LSFT(KC_2) , LSFT(KC_3) , KC_NO , KC_NO , KC_NO , KC_NO , KC_NO , KC_NO , KC_NO , KC_NO ,
        KC_NO , KC_NO , KC_NO , KC_NO , KC_NO , KC_NO , KC_NO , KC_NO , KC_NO , KC_NO ,
        KC_NO, KC_LEFT_SHIFT, KC_RIGHT_SHIFT, KC_NO
        ),
};
